
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftPORDIVIDIDOABS AND BAND BNOT BOR BXOR CADENA CHAR CORDER CORIZQ DECIMAL DIVIDIDO DOSPUNTOS ENTERO EXIT FLOAT GOTO ID IGUAL IGUALQ INT MAIN MAS MAYORIGUALQ MAYORQ MENORIGUALQ MENORQ MENOS NIGUALQ NOT OR PARDER PARIZQ POR PRINT PTCOMA READ RESIDUO REVALUAR SHIFTD SHIFTI UNSET VAR XORinit                   : MAIN DOSPUNTOS cuerpocuerpo               : instrucciones labels\n                            | labelslabels               : labels label\n                            | labellabel                  : ID DOSPUNTOS instruccionesinstrucciones          : instrucciones instruccioninstrucciones          : instruccioninstruccion          : asignacion\n                            asignacion             : VAR IGUAL ENTERO'
    
_lr_action_items = {'MAIN':([0,],[2,]),'$end':([1,4,6,7,8,9,12,13,14,17,18,],[0,-1,-3,-8,-5,-9,-2,-7,-4,-6,-10,]),'DOSPUNTOS':([2,10,],[3,15,]),'ID':([3,5,6,7,8,9,12,13,14,17,18,],[10,10,10,-8,-5,-9,10,-7,-4,-6,-10,]),'VAR':([3,5,7,9,13,15,17,18,],[11,11,-8,-9,-7,11,11,-10,]),'IGUAL':([11,],[16,]),'ENTERO':([16,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'cuerpo':([3,],[4,]),'instrucciones':([3,15,],[5,17,]),'labels':([3,5,],[6,12,]),'instruccion':([3,5,15,17,],[7,13,7,13,]),'label':([3,5,6,12,],[8,8,14,14,]),'asignacion':([3,5,15,17,],[9,9,9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> MAIN DOSPUNTOS cuerpo','init',3,'p_init','gramatica.py',159),
  ('cuerpo -> instrucciones labels','cuerpo',2,'p_cuerpo','gramatica.py',162),
  ('cuerpo -> labels','cuerpo',1,'p_cuerpo','gramatica.py',163),
  ('labels -> labels label','labels',2,'p_lista_label','gramatica.py',166),
  ('labels -> label','labels',1,'p_lista_label','gramatica.py',167),
  ('label -> ID DOSPUNTOS instrucciones','label',3,'p_label','gramatica.py',170),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_lista_instrucciones','gramatica.py',173),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_instruccion','gramatica.py',176),
  ('instruccion -> asignacion','instruccion',1,'p_instruccion','gramatica.py',179),
  ('asignacion -> VAR IGUAL ENTERO','asignacion',3,'p_asignacion','gramatica.py',183),
]
